### PR TITLE
update summary report text

### PR DESCRIPTION
**Pull request by tgerdesnv**
- Update summary sentence to explicitly name the best config
- Update summary memory consumption sentence to fix CPU bug and to correctly reference plots
- Remove batch sizes from summary report

### CODE REVIEW

**Comment by tgerdesnv** [comment]
gpu_summary_changes

**Review by dzier — APPROVED** [review]

**Comment by dzier** [comment]
Should still be reviewed by a team member. I am approving the overall report format and changes.

**Comment by tgerdesnv** [comment]
> > Should the whole sentence just be removed? We already said in the previous sentence that the plots only contain the top 3 configs, and the plots have clear titles and labels
> 
> Yes, I don't think it's needed. Remove or rewrite, I'm fine with either.

@dzier are you ok with removing the last sentence? It doesn't say anything new that isn't in the previous sentence or the chart title

**Comment by dzier** [comment]
That should be fine.

**Comment by tgerdesnv** [comment]
Bottom sentence is gone:
image

Also renamed "Preferred batch size" table header to "Dynamic Batching"

**Review by nv-braf — APPROVED** [review]
Approved!

**Pull request merged**
