### PR TITLE
Update colors for detail report legend

### PR DESCRIPTION
**Pull request by cvinson830**
1) View the labels inside six of the colors below.
- Notice three colors of the 'server compute' co-related items are 1) from the same shade, and 2) in the cool palette
- The other three unrelated items are 1) not of the same shade, and 2) from the warm palette

image

2) Resulting plot (for presentation purposes, some values were spoofed to show their contribution to the bar from a color perspective)
image

3) Fixed spacing
image

- Old (starting point before this PR)
image

### CODE REVIEW

**Comment by tgerdesnv** [comment]
I know the proposal was to mix warm and cool, but after seeing it I don't like it. The blues pop, but the 'warm' colors just look muted and dull.  A few possibilities:
1) Only use cool colors. Shades of blue for compute, and non-blue colors for the rest
2) Still use warm and cool, but eliminate red60, neutral 60, and dark neutral (which to me are the dull ones)
3) Swap warm and cool since a majority of the plot will be non-compute. Basically have compute be orange/red, and the others be cool colors (but not all blue)

**Comment by cvinson830** [comment]
> I know the proposal was to mix warm and cool, but after seeing it I don't like it. The blues pop, but the 'warm' colors just look muted and dull. A few possibilities:
> 
> 1. Only use cool colors. Shades of blue for compute, and non-blue colors for the rest
> 2. Still use warm and cool, but eliminate red60, neutral 60, and dark neutral (which to me are the dull ones)
> 3. Swap warm and cool since a majority of the plot will be non-compute. Basically have compute be orange/red, and the others be cool colors (but not all blue)

Option #2 selected

**Comment by tgerdesnv** [comment]
Looks good to me, although not all colors are showing. Is it hard to fudge the numbers in the chart and regenerate?

**Comment by cvinson830** [comment]
> Looks good to me, although not all colors are showing. Is it hard to fudge the numbers in the chart and regenerate?

I updated the comment up above.  Here it is for convenience
image

**Review by tgerdesnv — APPROVED** [review]

**Pull request merged**
